### PR TITLE
Clean ipynb

### PR DESCRIPTION
**Pull request by harahu**
You can have any colour you like as long as it's black.

### CODE REVIEW

**Comment by areeh** [comment]
What do you think about commenting out shell commands this once to make Black run on everything? It would be a one-off, so I'm not sure

**Review by areeh — APPROVED** [review]
LGTM

**Comment by kung-foo** [comment]
https://pypi.org/project/nb-black/

**Comment by harahu** [comment]
> What do you think about commenting out shell commands this once to make Black run on everything? It would be a one-off, so I'm not sure

Coming up in separate PR

**Comment by harahu** [comment]
> https://pypi.org/project/nb-black/

I modified this: https://github.com/Guardiome/clean_ipynb to suit my needs, but will give nb-black a go as well.

**Pull request merged**
